---
title: "Baysian Mini-PSC Detection"
author: Matt McCabe
date: "2025-05-13"
date-modified: last-modified
format: html
execute:
  freeze: true
---

This is just a short teaching document on a method for using Bayesian inference to detect miniature post-synaptic currents (mPSCs). As a grad student, I struggled with this quite a bit. A few weeks ago, I came back to it and found that this time around it was a whole lot easier. It's amazing what time and experience can do.

# Motivation

In the neuroscience world, and in synaptic physiology in particular, one of the things we care a lot about are mPSCs (aka "minis"). Minis are the result of individual synatpic vesicles being spontaneously released into the synaptic cleft. Since synaptic vesicles are the building blocks of synaptic transmission, understanding if they might be affected in disease states is something we're often interested in.

# Dummy Dataset
## Generating random events

The typical setup for these experiments involves sampling data at 1 kHz for a few minutes. During that time, you observe events at an apparently random interval. Here we're just going to simulate events occurring at a rate of 10 Hz, and we'll simulate 3 seconds of data. We'll do this using a Poisson distribution.


```{python}
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("bmh")

import scipy.stats as ss

seconds = np.linspace(0, 3, 3000)
events = ss.poisson(0.01).rvs(len(seconds))

fig, ax = plt.subplots(figsize=(10, 3))
ax.plot(seconds, events)

_ = ax.set(
    xlabel="Seconds",
    ylabel="Event",
    yticks=[0, 1],
    title="Event Times"
)
```

## Generating an event impulse

Now that we have event times, we need to generate the PSC waveform we observe that results from the synaptic event. Here we're going to base the waveform on Bekkers and Clements. 

```{python}
def make_impulse(amplitude=1, rise=3, decay=10, template_length=100):
    """
    Create an impulse response function.
    """
    return np.array(
        [
                -amplitude 
                * (1 - np.exp(-t / rise)) 
                * np.exp(-t/decay)
                for t in np.arange(template_length)
        ]
    )

impulse = make_impulse(amplitude=40)
fig, ax = plt.subplots()
ax.plot(impulse)
```

## Convolving the impulse with the event trace

Now that we have an event waveform, and a series of events, we will convolve them to generate the idealized PSC trace.

```{python}
true_trace = np.convolve(events, impulse, mode='same')

fig, ax = plt.subplots(figsize=(10, 3))
ax.plot(seconds, true_trace)

_ = ax.set(
    xlabel="Seconds",
    ylabel="pA",
    title="Idealized Event Trace"
)
```

## Adding in some noise

With all that in hand, now we need to make it resemble the real world by adding in a whole bunch of noise!

```{python}
noisy_trace = true_trace + np.random.normal(0, 5, len(true_trace))

fig, ax = plt.subplots(figsize=(10, 3))
ax.plot(seconds, noisy_trace)

_ = ax.set(
    xlabel="Seconds",
    ylabel="pA",
    title="Noisy Event Trace"
)
```

Those who have done physiology in the past will recognize this as a fairly close-to-reality for a synaptic trace trying to detect mPSCs. Now that we have some realistic-looking data in hand, we're going to try to recover our simulation parameters using Bayesian inference.

# Detecting events

First we need to define the convolution function we want to use. Full disclosure, I stole this directly from PyMC-Marketing, but it's a broadly useful convolution function.

```{python}
from enum import Enum
import pytensor.tensor as pt
from pytensor.npy_2_compat import normalize_axis_index

class ConvMode(str, Enum):
    """Convolution mode for the convolution."""

    After = "After"
    Before = "Before"
    Overlap = "Overlap"

def batched_convolution(
    x,
    w,
    axis: int = 0,
    mode: ConvMode | str = ConvMode.After,
):
    R"""Apply a 1D convolution in a vectorized way across multiple batch dimensions.

    .. plot::
        :context: close-figs

        import matplotlib.pyplot as plt
        import numpy as np
        import arviz as az
        from pymc_marketing.mmm.transformers import batched_convolution, ConvMode
        plt.style.use('arviz-darkgrid')
        spends = np.array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])
        w = np.array([0.75, 0.25, 0.125, 0.125])
        x = np.arange(-5, 6)
        ax = plt.subplot(111)
        for mode in [ConvMode.Before, ConvMode.Overlap, ConvMode.After]:
            y = batched_convolution(spends, w, mode=mode).eval()
            suffix = "\n(default)" if mode == ConvMode.After else ""
            plt.plot(x, y, label=f'{mode.value}{suffix}')
        plt.xlabel('time since spend', fontsize=12)
        plt.ylabel('f(time since spend)', fontsize=12)
        plt.title(f"1 spend at time 0 and {w = }", fontsize=14)
        box = ax.get_position()
        ax.set_position([box.x0, box.y0, box.width * 0.8, box.height])
        ax.legend(loc='center left', bbox_to_anchor=(1, 0.5))
        plt.show()

    Parameters
    ----------
    x : tensor_like
        The array to convolve.
    w : tensor_like
        The weight of the convolution. The last axis of ``w`` determines the number of steps
        to use in the convolution.
    axis : int
        The axis of ``x`` along witch to apply the convolution
    mode : ConvMode, optional
        The convolution mode determines how the convolution is applied at the boundaries
        of the input signal, denoted as "x." The default mode is ConvMode.After.

        - ConvMode.After: Applies the convolution with the "Adstock" effect, resulting in a trailing decay effect.
        - ConvMode.Before: Applies the convolution with the "Excitement" effect, creating a leading effect
          similar to the wow factor.
        - ConvMode.Overlap: Applies the convolution with both "Pull-Forward" and "Pull-Backward" effects,
          where the effect overlaps with both preceding and succeeding elements.

    Returns
    -------
    y : tensor_like
        The result of convolving ``x`` with ``w`` along the desired axis. The shape of the
        result will match the shape of ``x`` up to broadcasting with ``w``. The convolved
        axis will show the results of left padding zeros to ``x`` while applying the
        convolutions.

    """
    # We move the axis to the last dimension of the array so that it's easier to
    # reason about parameter broadcasting. We will move the axis back at the end
    x = pt.as_tensor(x)
    w = pt.as_tensor(w)

    axis = normalize_axis_index(axis, x.ndim)
    x = pt.moveaxis(x, axis, -1)
    x_batch_shape = tuple(x.shape)[:-1]
    lags = w.shape[-1]

    if mode == ConvMode.After:
        zeros = pt.zeros((*x_batch_shape, lags - 1), dtype=x.dtype)
        padded_x = pt.join(-1, zeros, x)
    elif mode == ConvMode.Before:
        zeros = pt.zeros((*x_batch_shape, lags - 1), dtype=x.dtype)
        padded_x = pt.join(-1, x, zeros)
    elif mode == ConvMode.Overlap:
        zeros_left = pt.zeros((*x_batch_shape, lags // 2), dtype=x.dtype)
        zeros_right = pt.zeros((*x_batch_shape, (lags - 1) // 2), dtype=x.dtype)
        padded_x = pt.join(-1, zeros_left, x, zeros_right)
    else:
        raise ValueError(f"Wrong Mode: {mode}, expected one of {', '.join(ConvMode)}")

    conv = pt.signal.convolve1d(padded_x, w, mode="valid")
    return pt.moveaxis(conv, -1, axis + conv.ndim - x.ndim)


def make_impulse(amplitude, rise, decay, template_length):
    """
    Create an impulse response function that's compatible with PyTensor symbolic variables.
    """
    t = pt.arange(template_length)
    rise_term = 1 - pt.exp(-t / rise)
    decay_term = pt.exp(-t / decay)
    return -amplitude * rise_term * decay_term
```

## Detection Model

With that out of the way, now we're going to develop our model. 

```{python}
import pymc as pm
import arviz as az

with pm.Model() as model:

    event_rate = pm.HalfNormal("event_rate", 0.1)
    
    amp = pm.Normal("amp", 20, 10)
    rise = pm.Normal("rise", 3, 1)
    decay = pm.Normal("decay", 10, 1)
    
    model_events = pm.Poisson("model_events", event_rate, shape=len(events))
    impulse = make_impulse(amp, rise, decay, 100)

    impulse_response = batched_convolution(
        model_events,
        impulse,
        axis=0,
        mode=ConvMode.After,
    )

    observed_sigma = pm.HalfNormal("observed_sigma", 0.1)
    observed = pm.Normal(
        "observed",
        mu=impulse_response,
        sigma=observed_sigma,
        observed=noisy_trace,
    )
```

## Detection in Action

```{python}
with model:
    idata = pm.sample_smc(chains=2)

az.plot_trace(idata, var_names=["event_rate", "amp", "rise", "decay", "observed_sigma"])
plt.tight_layout()
```
