project:
  type: website
  render:
    - index.qmd

website:
  title: "Matt McCabe, PhD"
  search: false

format:
  html:
    theme:
      - simplex
      - brand
    css: styles.css
    toc: false
    code-fold: false

execute:
  freeze: auto
